TEAM_SYNONYMS = {
    "академия ска": "Akademiya SKA Saint Petersburg",
    "алмаз": "Almaz Cherepovets",
    "амурские тигры": "Amurskie Tigry",
    "авангард": "Avangard Omsk",
    "авто": "Avto Yekaterinburg",
    "автомобилист": "Avtomobilist Ekaterinburg",
    "адмирал": "Admiral Vladivostok",
    "ак барс": "Ak Bars Kazan",
    "амур": "Amur Khabarovsk",
    "красная машина атлант": "Atlanty Mytishchi",
    "барыс": "Barys Astana",
    "белые медведи": "Belye Medvedi Chelyabinsk",
    "чайка": "Chaika Nizhny Novgorod",
    "динамо мн": "Dinamo Minsk",
    "динамо м": "Dynamo Moscow",
    "мхк динамо м": "MHK Dynamo Moscow",
    "мхк динамо спб": "Dinamo Saint Petersburg",
    "динамо-шинник": "Dinamo-Shinnik Bobruysk",
    "ирбис": "Irbis Kazan",
    "крылья советов": "JHC Krylya Sovetov",
    "красная армия": "Krasnaya Armiya",
    "красная машина": "Krasnaya Mashina",
    "красноярские рыси": "Krasnoyark Lynxes",
    "кузнецкие медведи": "Kuznetskie Medvedi",
    "лада": "Lada Togliatti",
    "локо": "Loko Yaroslavl",
    "локо-76": "Loko Yaroslavl",
    "локомотив": "Lokomotiv Yaroslavl",
    "мамонты югры": "Mamonty Yugry",
    "металлург мг": "Metallurg Magnitogorsk",
    "мхк молот": "Molot-Prikamye Perm",
    "академия михайлова": "Mikhailov Academy",
    "акм-юниор": "Mikhailov Academy",
    "нефтехимик": "Neftekhimik Nizhnekamsk",
    "омские ястребы": "Omskie Yastreby", 
    "реактор": "Reaktor Niznekamsk",
    "сахалинские акулы": "Sakhalin Sharks",
    "салават юлаев": "Salavat Yulaev Ufa",
    "северсталь": "Severstal Cherepovets",
    "сибирь": "Sibir Novosibrisk Region",
    "сибирские снайперы": "Sibirskie Snaipery",
    "ска": "SKA Saint Petersburg",
    "ска-1946": "SKA-1946 Saint Petersburg",
    "снежные барсы": "Snezhnye Barsy",
    "спартак": "Spartak Moscow",
    "мхк спартак": "MHK Spartak Moscow",
    "мхк спартак мах": "MHK Spartak Moscow",
    "спутник ал": "Sputnik Almetyevsk",
    "стальные лисы": "Stalnye Lisy",
    "тайфун": "Taifun Ussuriysk",
    "толпар": "Tolpar Ufa", 
    "торпедо": "Torpedo Nizhny Novgorod",
    "трактор": "Traktor Chelyabinsk",
    "хк сочи": "HC Sochi",
    "цска": "CSKA Moscow",
    "драконы": "Shanghai Dragons",
}

CITY_TO_ARENA = {
    "Ярославль": "Arena-2000 Lokomotiv",
    "Магнитогорск": "Arena Metallurg",
    "Ханты-Мансийск": "Arena Ugra",
    "Астана": "Barys Arena",
    "ФТ Сириус": "Bolshoy Ice Dome",
    "Москва": "CSKA Arena",
    "Владивосток": "Fetisov Arena",
    "Омск": "G-Drive Arena",
    "Череповец": "Ice Palace",
    "Тула": "Ice Sports Palace Tula",
    "Верхняя Пышма": "KRK Uralets",
    "Новокузнецк": "Kuznetsk Metallurgists Sports Palace",
    "Тольятти": "Lada Arena",
    # "Megasport": "Megasport Arena",
    "Минск": "Minsk Arena",
    "Нижний Новгород": "CEC Nagorny",
    "Нижнекамск": "Neftekhim Ice Palace",
    "Красноярск": "Platinum Arena",
    "Хабаровск": "Platinum Arena",
    "Санкт-Петербург": "SKA Arena",
    "Новосибирск": "Sibir Arena",
    "Казань": "Tatneft Arena",
    "Челябинск": "Traktor Ice Arena",
    "Уфа": "Ufa Arena",
    "Екатеринбург": "UMMC Arena",
    "Пермь": "Universal Sports Palace Molot",
    "Альметьевск": "Yubileyny Sports Palace",
}

KNOWN_ARENAS = {
    "Arena-2000 Lokomotiv",
    "Arena Metallurg",
    "Arena Ugra",
    "Barys Arena",
    "Bolshoy Ice Dome",
    "CEC Nagorny",
    "CSKA Arena",
    "Fetisov Arena",
    "G-Drive Arena",
    "Ice Palace",
    "KRK Uralets",
    "Kuznetsk Metallurgists Sports Palace",
    "Ice Sports Palace Tula",
    "Lada Arena",
    "Megasport Arena",
    "Minsk Arena",
    "Neftekhim Ice Palace",
    "Platinum Arena",
    "Sibir Arena",
    "SKA Arena",
    "Tatneft Arena",
    "Traktor Ice Arena",
    "Ufa Arena",
    "UMMC Arena",
    "Universal Sports Palace Molot",
    "VTB Arena",
    "Yubileyny Sports Palace",
}