TEAM_SYNONYMS = {
    "авангард": "Avangard Omsk",
    "автомобилист": "Avtomobilist Ekaterinburg",
    "адмирал": "Admiral Vladivostok",
    "ак барс": "Ak Bars Kazan",
    "амур": "Amur Khabarovsk",
    "барыс": "Barys Astana",
    "динамо мн": "Dinamo Minsk",
    "динамо м": "Dynamo Moscow",
    "лада": "Lada Togliatti",
    "локомотив": "Lokomotiv Yaroslavl",
    "металлург мг": "Metallurg Magnitogorsk",
    "нефтехимик": "Neftekhimik Nizhnekamsk",
    "салават юлаев": "Salavat Yulaev Ufa",
    "северсталь": "Severstal Cherepovets",
    "сибирь": "Sibir Novosibrisk Region",
    "ска": "SKA Saint Petersburg",
    "спартак": "Spartak Moscow",
    "торпедо": "Torpedo Nizhny Novgorod",
    "трактор": "Traktor Chelyabinsk",
    "хк сочи": "HC Sochi",
    "цска": "CSKA Moscow",
    "драконы": "Shanghai Dragons",
}

CITY_TO_ARENA = {
    "Ярославль": "Arena-2000 Lokomotiv",
    "Магнитогорск": "Arena Metallurg",
    "Астана": "Barys Arena",
    "ФТ Сириус": "Bolshoy Ice Dome",
    "Москва": "CSKA Arena",
    "Владивосток": "Fetisov Arena",
    "Омск": "G-Drive Arena",
    "Череповец": "Ice Palace",
    "Тольятти": "Lada Arena",
    # "Megasport": "Megasport Arena",
    "Минск": "Minsk Arena",
    "Нижний Новгород": "CEC Nagorny",
    "Нижнекамск": "Neftekhim Ice Palace",
    "Хабаровск": "Platinum Arena",
    "Санкт-Петербург": "SKA Arena",
    "Новосибирск": "Sibir Arena",
    "Казань": "Tatneft Arena",
    "Челябинск": "Traktor Ice Arena",
    "Уфа": "Ufa Arena",
    "Екатеринбург": "UMMC Arena",
}

KNOWN_ARENAS = {
    "Arena-2000 Lokomotiv",
    "Arena Metallurg",
    "Barys Arena",
    "Bolshoy Ice Dome",
    "CEC Nagorny",
    "CSKA Arena",
    "Fetisov Arena",
    "G-Drive Arena",
    "Ice Palace",
    "Lada Arena",
    "Megasport Arena",
    "Minsk Arena",
    "Neftekhim Ice Palace",
    "Platinum Arena",
    "Sibir Arena",
    "SKA Arena",
    "Tatneft Arena",
    "Traktor Ice Arena",
    "Ufa Arena",
    "UMMC Arena",
    "VTB Arena",
}