TEAM_STADIUM = {
    "arizona state sun devils": "Mullett Arena",
    "augustana vikings": "Midco Arena",
    "bemidji state beavers": "Sanford Center",
    "bowling green falcons": "Slater Family Ice Arena",
    "colorado college tigers": "Ed Robson Arena",
    "ferris state bulldogs": "Robert L. Ewigleben Ice Arena",
    "lake superior state lakers": "Taffy Abel Arena",
    "merrimack warriors": "Lawler Rink",
    "miami redhawks": "Goggin Ice Center",
    "michigan tech huskies": "John MacInnes Student Ice Arena",
    "michigan wolverines": "Yost Ice Arena",
    "minnesota duluth bulldogs": "AMSOIL Arena",
    "minnesota golden gophers": "3M Arena at Mariucci",
    "minnesota state mavericks": "Mayo Clinic HSEC",
    "nebraska mavericks": "Baxter Arena",
    "north dakota fighting hawks": "Ralph Engelstad Arena",
    "northern michigan wildcats": "Berry Events Center",
    "notre dame fighting irish": "Compton Family Ice Arena",
    "st. cloud state huskies": "Herb Brooks National Hockey Center",
    "st. thomas tommies": "Lee & Penny Anderson Arena",
    "western michigan broncos": "Lawson Arena"
}

CITY_TO_ARENA = {
    "": "To be determined",
    "Amherst, MA": "Mullins Center",
    "Anchorage, Alaska": "Seawolf Sports Complex",
    "Ann Arbor, MI": "Yost Ice Arena",
    "Ann Arbor, Mich.": "Yost Ice Arena",
    "Austin, Texas": "H-E-B Center",
    "Bemidji, Minn.": "Sanford Center",
    "Bemidji, MN": "Sanford Center",
    "Big Rapids, Mich.": "Ewigleben Ice Arena",
    "Big Rapids, MI": "Ewigleben Ice Arena",
    "Boston, Mass.": "Matthews Arena",
    "Boston, MA (TD Garden)": "TD Garden",
    "Bowling Green, Ohio": "Slater Family Ice Arena",
    "Bowling Green, OH": "Slater Family Ice Arena",
    "Brainerd, Minn.": "Essentia health Sports Center",
    "Burlington, VT.": "Gutterson Fieldhouse",
    "Burlington, VT": "Gutterson Fieldhouse",
    "Cambridge, MA": "Bright-Landry Hockey Center",
    "Canton, NY": "Appleton Arena",
    "Chestnut Hill, MA": "Conte Forum",
    "Chestnut Hill, Mass.": "Conte Forum",
    "Colorado springs, Colo.": "Ed Robson Arena",
    "Columbus, OH": "Value City Arena",
    "Columbus, Ohio": "Value City Arena",
    "Denver, Colo.": "Magness Arena",
    "Denver, CO": "Magness Arena",
    "Duluth Minn.": "AMSOIL Arena",
    "Duluth, MN": "AMSOIL Arena",
    "Durham, NH": "Whittemore Center",
    "East Lansing, Mich.": "Munn Ice Arena",
    "East Lansing, MI": "Munn Ice Arena",
    "Fairbanks, AK": "Carlson Center",
    "Grand Forks, N.D.": "Ralph Engelstad Arena",
    "Grand Forks, ND": "Ralph Engelstad Arena",
    "Grand Rapids, Mich.": "Van Andel Arena",
    "Hamden, CT": "M&T Bank Arena",
    "Hamilton, NY": "Class of 1965 Arena",
    "Hanover, NH": "Thompson Arena",
    "Houghton, MI": "John MacInnes Student Ice Arena",
    "Ithaca, NY": "Lynah Rink",
    "Kalamazoo, MI": "Lawson Ice Arena",
    "Kalamazoo, Mich.": "Lawson Ice Arena",
    "Kalamazoo, Mich. (Waldo Stadium)": "Waldo Stadium",
    "Lawler Rink": "Lawler Arena",
    "Lawson Arena": "Lawson Ice Arena",
    "Lowell, MA": "Tsongas Center",
    "Madison, WI": "Kohl Center",
    "Madison, Wis.": "Kohl Center",
    "Mankato, MN": "Mayo Clinic HSEC",
    "Marquette, Mich.": "Berry Events Center",
    "Marquette, MI": "Berry Events Center",
    "Minneapolis": "3M Arena at Mariucci",
    "Minneapolis, MN": "3M Arena at Mariucci",
    "Minneapolis, Minn.": "3M Arena at Mariucci",
    "Moon Township, Pa.": "RMU Island Sports Center",
    "M & T Bank Arena": "M&T Bank Arena",
    "New Haven, CT": "Ingalls Rink",
    "North Andover, MA": "Lawler Rink",
    "Omaha, Neb.": "Baxter Arena",
    "Omaha, NE": "Baxter Arena",
    "Orono, ME": "Alfond Arena",
    "Orono, Maine": "Alfond Arena",
    "Oxford, Ohio": "Goggin Ice Center",
    "Oxford, Ohio.": "Goggin Ice Center",
    "Oxford, OH": "Goggin Ice Center",
    "Oxford\\, Ohio.": "Goggin Ice Center",
    "Plymouth, Mich.": "USA Hockey Arena",
    "Potsdam, NY": "Cheel Arena",
    "Princeton, NJ": "Hobey Baker Rink",
    "Providence, RI": "Schneider Arena",
    "Robert L. Ewigleben Ice Arena": "Ewigleben Ice Arena",
    "Sault Ste. Marie, MI": "Taffy Abel Arena",
    "Schenectady, NY": "M&T Bank Center",
    "Sioux Falls, SD": "Midco Arena",
    "South Bend, Ind.": "Compton Family Ice Arena",
    "South Bend, IN": "Compton Family Ice Arena",
    "Storrs, CT": "Toscano Ice Forum",
    "St. Cloud, Minn.": "Herb Brooks National Hockey Center",
    "St. Cloud, MN": "Herb Brooks National Hockey Center",
    "St. Paul, Minn.": "Lee & Penny Anderson Arena",
    "St. Paul, MN": "Lee & Penny Anderson Arena",
    "Steve Cady Arena": "Goggin Ice Center",
    "TBD": "To be determined",
    "Tempe, Ariz.": "Mullett Arena",
    "Tempe, AZ": "Mullett Arena",
    "Troy, NY": "Houston Field House",
    "University Park, Pa": "Pegula Ice Arena",
    "University Park, Pa.": "Pegula Ice Arena",
}

KNOWN_ARENAS = {
    "3M Arena at Mariucci",
    "Agganis Arena",
    "Alfond Arena",
    "AMSOIL Arena",
    "Appleton Arena",
    "Baxter Arena",
    "Berry Events Center",
    "Brainerd International Raceway",
    "Bright-Landry Hockey Center",
    "Carlson Center",
    "Cheel Arena",
    "Class of 1965 Arena",
    "Compton Family Ice Arena",
    "Conte Forum",
    "Ed Robson Arena",
    "Essentia health Sports Center",
    "Ewigleben Ice Arena",
    "Goggin Ice Center",
    "Gutterson Fieldhouse",
    "H-E-B Center",
    "Herb Brooks National Hockey Center",
    "Hobey Baker Rink",
    "Houston Field House",
    "Ingalls Rink",
    "John MacInnes Student Ice Arena",
    "Kohl Center",
    "Kreitzberg Arena",
    "Lawler Arena",
    "Lawler Rink",
    "Lawson Ice Arena",
    "Lee & Penny Anderson Arena",
    "Lynah Rink",
    "Magness Arena",
    "Matthews Arena",
    "Mayo Clinic HSEC",
    "Meehan Auditorium",
    "Midco Arena",
    "Mullett Arena",
    "Mullins Center",
    "Munn Ice Arena",
    "M&T Bank Arena",
    "M&T Bank Center",
    "Pegula Ice Arena",
    "Ralph Engelstad Arena",
    "RMU Island Sports Center",
    "Sanford Center",
    "Schneider Arena",
    "Seawolf Sports Complex",
    "Slater Family Ice Arena",
    "Stafford-Smith Field at Waldo Stadium",
    "T-Mobile Arena",
    "Taffy Abel Arena",
    "TD Garden",
    "The O2 Belfast",
    "Thompson Arena",
    "To be determined",
    "Toscano Ice Forum",
    "Tsongas Center",
    "USA Hockey Arena",
    "Value City Arena",
    "Van Andel Arena",
    "Waldo Stadium",
    "Whittemore Center",
    "Yost Ice Arena",
}

NCAA_MASCOT_FIX = {
    "Fighting Sioux": "Fighting Hawks"
}

NCAA_TEAM_FIX = {
    "Alaska Fairbanks": "Alaska",
    "Army": "Army West Point",
    "Boston": "Boston University",
    "Merrimack College": "Merrimack",
    "LIU": "Long Island",
    "Providence/Minnesota-Duluth": "To be determined",
    "Rensselaer Polytechnic Institute": "RPI",
    "UConn/Colgate": "To be determined",
    "UConn/Colgate/Providence": "To be determined",
    "UMass": "UMass Lowell",
    "Union College": "Union",
    "United States National Team Development Program": "US National Team Development Program",
    "U.S. Under-18 Team": "US National Team Development Program",
    "USA Hockey Under-18 Team": "US National Team Development Program",
    "Wisconsin/UMass/NMU": "To be determined",
}

TEAM_NORMALIZATION = {
    "Dartmouth College Big Green": "Dartmouth College",
    "Denver Pioneers": "Denver",
    "Miami Redhawks": "Miami",
    "St. Cloud State Huskies": "St. Cloud State",
    "Western Michigan Broncos": "Western Michigan",
}

TEAM_MASCOTS_FALLBACK = {
    "Air Force": "Falcons",
    "Alaska": "Nanooks",
    "Alaska Anchorage": "Seawolves",
    "Arizona State": "Sun Devils",
    "Army West Point": "Black Knights",
    "Augustana": "Vikings",
    "Bemidji State": "Beavers",
    "Bentley": "Falcons",
    "Bowling Green": "Falcons",
    "Boston College": "Eagles",
    "Boston University": "Terriers",
    "Brown": "Bears",
    "Canisius": "Golden Griffins",
    "Clarkson": "Golden Knights",
    "Colgate": "Raiders",
    "Colorado College": "Tigers",
    "Cornell": "Big Red",
    "Dartmouth College": "Big Green",
    "Denver": "Pioneers",
    "Ferris State": "Bulldogs",
    "Great Lakes Invitational": " ",
    "Guelph": "Gryphons",
    "Harvard": "Crimson",
    "Holy Cross": "Crusaders",
    "Ice Breaker": "To be determined",
    "Kwik Trip Holiday Face-Off": "To be determined",
    "Lake Superior State": "Lakers",
    "Lindenwood" :"Lions",
    "LIU or Army": "To be determined",
    "Long Island": "Sharks",
    "Maine": "Black Bears",
    "Manitoba": "Bisons",
    "Maryville": "Saints", 
    "Massachusetts": "Minutemen",
    "Merrimack": "Warriors",
    "Miami": "RedHawks",
    "Michigan": "Wolverines",
    "Michigan State": "Spartans",
    "Michigan Tech": "Huskies",
    "Minnesota": "Golden Gophers",
    "Minnesota Duluth": "Bulldogs",
    "Minnesota State": "Mavericks",
    "New Hampshire": "Wildcats",
    "Niagara": "Purple Eagles", 
    "North Dakota": "Fighting Hawks",
    "Northeastern": "Huskies",
    "Northern Michigan": "Wildcats",
    "Norwich": "Cadets",
    "Notre Dame": "Fighting Irish",
    "Ohio State": "Buckeyes",
    "Omaha": "Mavericks",
    "OttawaU": "Gee-Gees",
    "Penn State": "Nittany Lions", 
    "Princeton": "Tigers",
    "Providence": "Friars",
    "Quinnipiac": "Bobcats",
    "RPI": "Engineers",
    "RIT": "Tigers",
    "Robert Morris": "Colonials",
    "Sacred Heart": "Pionneers",
    "Stonehill": "Skyhawks",
    "St. Cloud State": "Huskies",
    "St. Lawrence": "Saints",
    "St. Thomas": "Tommies",
    "TBA | Empire State Holiday Invitational": "To be determined",
    "To be determined": " ",
    "UConn": "Huskies", 
    "UMass Lowell": "River Hawks", 
    "Union": "Garnet Chargers",
    "US National Team Development Program": " ",
    "Vermont": "Catamounts",
    "Waterloo": "Warriors",
    "Western Michigan": "Broncos",
    "Western Ontario": "Mustangs",
    "Windsor": "Lancers",
    "Wisconsin": "Badgers",
    "Yale": "Bulldogs",
}
