name: Update hockey calendar

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-calendar:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate calendar
        run: |
          python merge.py

      - name: Save calendar
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add calendar.ics

          git commit -m "Update calendar" || exit 0

          git push
